digital-wallet-platform:
  services:
    analytics-service:
      uri: ${ANALYTICS_SERVICE_BASE_URL}
    auth-service:
      uri: ${AUTH_SERVICE_BASE_URL}
    card-service:
      uri: ${CARD_SERVICE_BASE_URL}
    notification-service:
      uri: ${NOTIFICATION_SERVICE_BASE_URL}
    transaction-service:
      uri: ${TRANSACTION_SERVICE_BASE_URL}
    transaction-generator:
      uri: ${TRANSACTION_GENERATOR_BASE_URL}
    user-service:
      uri: ${USER_SERVICE_BASE_URL}
    wallet-service:
      uri: ${WALLET_SERVICE_BASE_URL}

server:
  port: 8001

spring:
  application:
    name: auth-service
  config:
    import: optional:file:.env[.properties]
  cache:
    type: redis
    cache-names: redis-cache
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  datasource:
    username: ${POSTGRES_USERNAME}
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_AUTH_SERVICE_DB}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    hibernate:
      ddl-auto: none
    show-sql: false


security:
  jwt:
    secret: ${JWT_SECRET}
    expirationMs: 604800000 # 1 week

unverified-user:
  ttl:
    sec: 900

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true