digital-wallet-platform:
  services:
    analytics-service:
      uri: ${ANALYTICS_SERVICE_BASE_URL}
    auth-service:
      uri: ${AUTH_SERVICE_BASE_URL}
    card-service:
      uri: ${CARD_SERVICE_BASE_URL}
    notification-service:
      uri: ${NOTIFICATION_SERVICE_BASE_URL}
    transaction-service:
      uri: ${TRANSACTION_SERVICE_BASE_URL}
    transaction-generator:
      uri: ${TRANSACTION_GENERATOR_BASE_URL}
    user-service:
      uri: ${USER_SERVICE_BASE_URL}
    wallet-service:
      uri: ${WALLET_SERVICE_BASE_URL}

server:
  port: 8007

spring:
  application:
    name: notification-service
  config:
    import: optional:file:.env[.properties]
  mail:
    host: ${MAILDEV_SPRING_MAIL_HOST}
    port: ${MAILDEV_SPRING_MAIL_PORT}
    username: ${MAILDEV_SPRING_MAIL_USERNAME}
    password: ${MAILDEV_SPRING_MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail.transport.protocol: smtp
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    prefer-ip-address: false
    ip-address: 127.0.0.1