version: "3.8"

services:
  postgres:
    container_name: "postgres"
    env_file:
      - .env
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5

  pgadmin:
    container_name: "pg-admin"
    env_file:
      - .env
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:80/misc/ping || exit -1
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5

  redis:
    container_name: "redis"
    env_file:
      - .env
    image: redis:7.2-alpine
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
    command: redis-server --save 20 1
    volumes:
      - cache:/data
    networks:
      - app-network

  maildev:
    container_name: "maildev"
    env_file:
      - .env
    image: maildev/maildev
    restart: unless-stopped
    environment:
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    networks:
      - app-network
    ports:
      - "1080:1080"
      - "1025:1025"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

  kafka-1:
    container_name: "kafka-1"
    env_file:
      - .env
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    restart: unless-stopped
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=qJ4ml6nfTtqCwijUCtOuwA
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9091,2@kafka-2:9091,3@kafka-3:9091
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9090,EXTERNAL://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL=http://schema-registry:8081
    volumes:
      - ${KAFKA_LOG_DIR_1}:/bitnami/kafka

  kafka-2:
    container_name: "kafka-2"
    env_file:
      - .env
    image: bitnami/kafka:latest
    ports:
      - "9094:9094"
    restart: unless-stopped
    environment:
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_KRAFT_CLUSTER_ID=qJ4ml6nfTtqCwijUCtOuwA
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9091,2@kafka-2:9091,3@kafka-3:9091
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-2:9090,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL=http://schema-registry:8081
    volumes:
      - ${KAFKA_LOG_DIR_2}:/bitnami/kafka

  kafka-3:
    container_name: "kafka-3"
    env_file:
      - .env
    image: bitnami/kafka:latest
    ports:
      - "9096:9096"
    restart: unless-stopped
    environment:
      - KAFKA_CFG_NODE_ID=3
      - KAFKA_KRAFT_CLUSTER_ID=qJ4ml6nfTtqCwijUCtOuwA
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9091,2@kafka-2:9091,3@kafka-3:9091
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9096
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-3:9090,EXTERNAL://localhost:9096
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL=http://schema-registry:8081
    volumes:
      - ${KAFKA_LOG_DIR_3}:/bitnami/kafka

  kafka-ui:
    container_name: "kafka-ui"
    env_file:
      - .env
    image: provectuslabs/kafka-ui:latest
    restart: unless-stopped
    ports:
      - "8989:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: qJ4ml6nfTtqCwijUCtOuwA
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-1:9090, kafka-2:9090, kafka-3:9090
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit -1
      interval: 10s
      timeout: 5s
      start_period: 60s
      retries: 5

  transaction-generator:
    container_name: "transaction-generator"
    build: ./transaction-generator
    ports:
      - "8101:8101"
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - app-network

  otp-service:
    container_name: "otp-service"
    build:
      context: .
      dockerfile: otp-service/Dockerfile
    ports:
      - "8100:8100"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - app-network

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge
  app-network:
    driver: bridge

volumes:
  postgres:
    driver: local
  pgadmin:
    driver: local
  cache:
    driver: local