global:
  scrape_interval: 5s

  external_labels:
    monitor: 'open-wallet-monitor'

scrape_configs:
  - job_name: 'open-wallet'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8004' ]
        labels:
          application: 'card-service'