digital-wallet-platform:
  services:
    analytics-service:
      uri: ${ANALYTICS_SERVICE_BASE_URL}
    auth-service:
      uri: ${AUTH_SERVICE_BASE_URL}
    card-service:
      uri: ${CARD_SERVICE_BASE_URL}
    notification-service:
      uri: ${NOTIFICATION_SERVICE_BASE_URL}
    transaction-service:
      uri: ${TRANSACTION_SERVICE_BASE_URL}
    transaction-generator:
      uri: ${TRANSACTION_GENERATOR_BASE_URL}
    user-service:
      uri: ${USER_SERVICE_BASE_URL}
    wallet-service:
      uri: ${WALLET_SERVICE_BASE_URL}

server:
  port: 8008

spring:
  application:
    name: analytics-service
  config:
    import: optional:file:.env[.properties]
  datasource:
    username: ${POSTGRES_USERNAME}
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_ANALYTICS_SERVICE_DB}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    hibernate:
      ddl-auto: none
    show-sql: false
  cloud:
    openfeign:
      okhttp:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

security:
  jwt:
    secret: ${JWT_SECRET}
    expirationMs: 604800000 # 1 week