digital-wallet-platform:
  services:
    analytics-service:
      uri: ${ANALYTICS_SERVICE_BASE_URL}
    auth-service:
      uri: ${AUTH_SERVICE_BASE_URL}
    card-service:
      uri: ${CARD_SERVICE_BASE_URL}
    notification-service:
      uri: ${NOTIFICATION_SERVICE_BASE_URL}
    transaction-service:
      uri: ${TRANSACTION_SERVICE_BASE_URL}
    transaction-generator:
      uri: ${TRANSACTION_GENERATOR_BASE_URL}
    user-service:
      uri: ${USER_SERVICE_BASE_URL}
    wallet-service:
      uri: ${WALLET_SERVICE_BASE_URL}

server:
  port: 8008

spring:
  application:
    name: analytics-service
  config:
    import: optional:file:.env[.properties]
  liquibase:
    enabled: false
  datasource:
    driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
    url: jdbc:clickhouse://${CLICKHOUSE_HOST}:${CLICKHOUSE_PORT}/${CLICKHOUSE_ANALYTICS_SERVICE_DB}?compress=0
    username: ${CLICKHOUSE_USER}
    password: ${CLICKHOUSE_PASSWORD}
  cloud:
    openfeign:
      micrometer:
        enabled: true
      client:
        config:
          default:
            logger-level: basic
      okhttp:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: ${EUREKA_CLIENT_REGISTRY_FETCH_INTERVAL}
  instance:
    lease-renewal-interval-in-seconds: ${EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL}
    lease-expiration-duration-in-seconds: ${EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION}
    hostname: ${EUREKA_INSTANCE_HOSTNAME}
    prefer-ip-address: false
    ip-address: ${EUREKA_INSTANCE_IP_ADDRESS}

management:
  tracing:
    sampling:
      probability: ${TRACING_PROBABILITY}
    propagation:
      type: b3
    baggage:
      enabled: true
      remote-fields: service-instance, service-port
    enabled: true
    include-eureka-healthcheck: false
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST}:${ZIPKIN_PORT}/api/v2/spans
      export:
        enabled: true

logging:
  pattern:
    level: "%5p [${spring.application.name}] [port:${server.port}]"

security:
  jwt:
    secret: ${JWT_SECRET}
    expirationMs: ${JWT_EXPIRATION_TIME_MS}

ai:
  api-key: ${AI_API_KEY}
  base-url: ${AI_BASE_URL}