digital-wallet-platform:
  services:
    analytics-service:
      uri: ${ANALYTICS_SERVICE_BASE_URL}
    auth-service:
      uri: ${AUTH_SERVICE_BASE_URL}
    card-service:
      uri: ${CARD_SERVICE_BASE_URL}
    notification-service:
      uri: ${NOTIFICATION_SERVICE_BASE_URL}
    transaction-service:
      uri: ${TRANSACTION_SERVICE_BASE_URL}
    transaction-generator:
      uri: ${TRANSACTION_GENERATOR_BASE_URL}
    user-service:
      uri: ${USER_SERVICE_BASE_URL}
    wallet-service:
      uri: ${WALLET_SERVICE_BASE_URL}

server:
  port: 8004

spring:
  application:
    name: card-service
  config:
    import: optional:file:.env[.properties]
  datasource:
    username: ${POSTGRES_USERNAME}
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_CARD_SERVICE_DB}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    hibernate:
      ddl-auto: none
    show-sql: false
  cloud:
    openfeign:
      micrometer:
        enabled: true
      client:
        config:
          default:
            logger-level: basic
      okhttp:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/
    register-with-eureka: false
    fetch-registry: true
    registry-fetch-interval-seconds: ${EUREKA_CLIENT_REGISTRY_FETCH_INTERVAL}
  instance:
    lease-renewal-interval-in-seconds: ${EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL}
    lease-expiration-duration-in-seconds: ${EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION}
    hostname: ${EUREKA_INSTANCE_HOSTNAME}
    prefer-ip-address: false
    ip-address: ${EUREKA_INSTANCE_IP_ADDRESS}

management:
  tracing:
    sampling:
      probability: ${TRACING_PROBABILITY}
    propagation:
      type: b3
    baggage:
      enabled: true
      remote-fields: service-instance, service-port
    enabled: true
    include-eureka-healthcheck: false
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST}:${ZIPKIN_PORT}/api/v2/spans
      export:
        enabled: true

logging:
  pattern:
    level: "%5p [${spring.application.name}] [port:${server.port}]"

security:
  jwt:
    secret: ${JWT_SECRET}
    expirationMs: ${JWY_EXPIRATION_TIME_MS}

payment:
  limits:
    per-transaction-amount: 1000000000.00